### PR TITLE
Support multi-byte characters

### PR DESCRIPTION
**Pull request by FromAtom**
Added support for multi-byte characters such as emoji and CJK.

### CODE REVIEW

**Comment by ireneu** [comment]
Hi @FromAtom, thanks for your interest in this project ! ☺️

I'm not convinced that using the UTF-16 view is the right solution to support multi-byte characters, since Swift handles this really well IMHO.

As an example, I've adapted your test changesets below so that they work with the existing code. Wouldn't this suit your needs? Let me know what you think!

```
import XCTest
@testable import Swot

final class SwotMultiByteCharTests: XCTestCase {
    let jsonChangeset = """
        {
            "operations": [
                {
                    "type": "keep",
                    "value": 6
                },
                {
                    "type": "add",
                    "value": "asdf"
                },
                {
                    "type": "remove",
                    "value": 3
                },
                {
                    "type": "keep",
                    "value": 4
                },
                {
                    "type": "add",
                    "value": "zxcv"
                }
            ]
        }
    """
    let anotherChangeset = Changeset(operations: [
        Keep(value: 1),
        Remove(value: 1),
        Keep(value: 2),
        Add(value: " a"),
        Keep(value: 1),
        Add(value: "e "),
        Keep(value: 3),
        Remove(value: 5),
        Add(value: "ty🍴"),
        Keep(value: 1),
        Remove(value: 4)
    ])
    let yetAnotherChangeset = Changeset(operations: [
        Remove(value: 4),
        Add(value: " ab"),
        Keep(value: 3),
        Remove(value: 5),
        Add(value: "ty"),
        Keep(value: 5),
        Remove(value: 1)
    ])

    let baseText = "👨‍👩‍👧qwerty poiu!"
    let firstApply = "👨‍👩‍👧qwertasdfoiu!zxcv"

    func testChangesetApply() {
        let decoder = JSONDecoder()
        let changeset = try! decoder.decode(Changeset.self, from: jsonChangeset.data(using: .utf8)!)

        let result = try! changeset.apply(to: baseText)

        XCTAssert(result == firstApply)
    }

    func testChangesetComposing() {
        let decoder = JSONDecoder()
        let changeset = try! decoder.decode(Changeset.self, from: jsonChangeset.data(using: .utf8)!)

        let transformedText = try! changeset.apply(to: baseText)
        let retransformedText = try! anotherChangeset.apply(to: transformedText)

        XCTAssert(retransformedText == "👨‍👩‍👧we are tasty🍴!")

        let chained = try! changeset >>> anotherChangeset
        let chainedApplyText = try! chained.apply(to: baseText)

        XCTAssert(chainedApplyText == "👨‍👩‍👧we are tasty🍴!")
    }

    func testChangesetCombining() {
        let combined = try! anotherChangeset <~> yetAnotherChangeset

        let resa = try! combined.right.apply(to: anotherChangeset.apply(to: firstApply))
        let resb = try! combined.left.apply(to: yetAnotherChangeset.apply(to: firstApply))

        XCTAssert(resa == resb)
    }

    func testChangeSetComposingWithMultiByteChars() {
        let basetext = "A"
        let changeset1 = Changeset(operations: [
            Add(value: "👨‍👩‍👧"),
            Keep(value: 1),
            Add(value: "X")
        ])
        let changeset2 = Changeset(operations: [
            Keep(value: 3),
            Add(value: "YZ")
        ])

        let chained = try! changeset1 >>> changeset2
        let chainedApplyText = try! chained.apply(to: basetext)

        XCTAssert(chainedApplyText == "👨‍👩‍👧AXYZ")
    }

    static var allTests = [
        ("testChangesetApply", testChangesetApply),
        ("testChangesetComposing", testChangesetComposing),
        ("testChangesetCombining", testChangesetCombining),
        ("testChangeSetComposingWithMultiByteChars", testChangeSetComposingWithMultiByteChars),
    ]
}
```

**Comment by FromAtom** [comment]
Hi!

@ireneu Thanks for the reply. I am also very grateful that you even provided the existing code.

But unfortunately, this method does not solve the problem I have. In fact, when I use swot using only Swift, this test case and the implementation so far are fine. However, many OT implementations work with the server side. In this case, `👨‍👩‍👧` is sent as 8 characters, so swot needs to handle `👨‍👩‍👧` as 8 characters.

You can see the same thing in http://operational-transformation.github.io/index.html, which is a visualization implementation of OT.

**Comment by ireneu** [comment]
Hi @FromAtom,

I understand what you mean. However, where Javascript says `'👨‍👩‍👧'.length == 8`, Python says `len('👨‍👩‍👧') == 5`, swift counts it as 1, and I'm sure we could find other results. This means that using the UTF-16 view works in this specific case, and it may break when dealing with other representations.

I personally prefer how Swift manages this and I hope that unicode support will be more uniform across languages in the future.

Considering this, I don't think it makes sense for me to merge this pull request. I hope you understand. You are free to use your fork and thank you for contributing ☺️

**Comment by FromAtom** [comment]
Hi @ireneu 

Thank you for your detailed explanation. It was very clear to me that my P-R is incomplete.
I appreciate your review and comments!

**Pull request closed without merging**
